// routes/items.js
// All authenticated roles may view inventory (needed by HOD to raise requisitions).
// Only superadmin and ictadmin may create/edit inventory item master records and
// manage packaging tiers. Only inventoryadmin (or superadmin/ictadmin) may record
// incoming stock receipts.
//
// Accounting model: `quantity_on_hand` and `reorder_level` are always stored in the
// item's indivisible BASE unit (e.g. "piece", "sheet"). A pack of 12 pencils is not
// the same thing as a pack of 24, or a single pencil — so every item can define any
// number of "packagings" (conversion tiers), each with a label and how many base
// units it represents. Receiving stock or raising a requisition is done by picking
// a packaging + a pack quantity; the server converts that to base units for all
// arithmetic, so stock levels are always exact regardless of which pack size was
// used at the counter.
const express = require("express");
const { db, audit, nowIso, nextItemCode, notifyRoles, checkLowStockAndNotify } = require("../db/init");
const { requireAuth, requireRole } = require("../middleware/auth");

const router = express.Router();
router.use(requireAuth);

const CAN_MANAGE_ITEMS = ["superadmin", "ictadmin"];
const CAN_RECEIVE_STOCK = ["inventoryadmin", "superadmin", "ictadmin"];

function getPackagings(itemId, includeInactive = false) {
  if (includeInactive) {
    return db
      .prepare("SELECT * FROM item_packagings WHERE item_id = ? ORDER BY units_per_pack ASC")
      .all(itemId);
  }
  return db
    .prepare("SELECT * FROM item_packagings WHERE item_id = ? AND is_active = 1 ORDER BY units_per_pack ASC")
    .all(itemId);
}

// Greedy breakdown of a base-unit quantity into the friendliest combination of
// packaging tiers, e.g. 500 pencils -> "20 x Pack of 24, 1 x Pack of 12, 8 x Single".
function breakdownQuantity(qty, packagings) {
  let remaining = Math.floor(Number(qty) || 0);
  const sorted = [...packagings].sort((a, b) => b.units_per_pack - a.units_per_pack);
  const parts = [];
  for (const p of sorted) {
    const per = Math.floor(p.units_per_pack);
    if (per <= 0) continue;
    const count = Math.floor(remaining / per);
    if (count > 0) {
      parts.push({ label: p.label, units_per_pack: p.units_per_pack, count });
      remaining -= count * per;
    }
  }
  return { parts, remainder: remaining };
}

function attachExtras(item) {
  const packagings = getPackagings(item.id);
  const defaultPkg = packagings.find((p) => p.is_default) || packagings[0] || null;
  const breakdown = breakdownQuantity(item.quantity_on_hand, packagings);
  return { ...item, packagings, default_packaging: defaultPkg, breakdown };
}

router.get("/", (req, res) => {
  const { q, category_id, status, include_inactive } = req.query;
  let sql = `
    SELECT i.*, c.name AS category_name, c.code AS category_code
    FROM items i
    LEFT JOIN categories c ON c.id = i.category_id
    WHERE 1=1`;
  const params = [];
  if (!include_inactive || include_inactive === "0") {
    sql += " AND i.is_active = 1";
  }
  if (category_id) {
    sql += " AND i.category_id = ?";
    params.push(category_id);
  }
  if (q) {
    sql += " AND (i.name LIKE ? OR i.code LIKE ? OR i.description LIKE ?)";
    params.push(`%${q}%`, `%${q}%`, `%${q}%`);
  }
  sql += " ORDER BY i.name ASC";

  let items = db.prepare(sql).all(...params);
  if (status === "low") items = items.filter((i) => i.quantity_on_hand <= i.reorder_level);
  if (status === "healthy") items = items.filter((i) => i.quantity_on_hand > i.reorder_level);

  items = items.map(attachExtras);
  res.json({ items });
});

router.get("/:id", (req, res) => {
  const item = db
    .prepare(
      `SELECT i.*, c.name AS category_name, c.code AS category_code
       FROM items i LEFT JOIN categories c ON c.id = i.category_id WHERE i.id = ?`
    )
    .get(req.params.id);
  if (!item) return res.status(404).json({ error: "Item not found." });
  res.json({ item: attachExtras(item) });
});

router.post("/", requireRole(...CAN_MANAGE_ITEMS), (req, res) => {
  const { name, description, unit, category_id, reorder_level, quantity_on_hand, packagings } = req.body || {};
  if (!name || !unit) {
    return res.status(400).json({ error: "Item name and base unit are required." });
  }
  if (!category_id) {
    return res.status(400).json({ error: "Please choose a category for this item." });
  }
  const category = db.prepare("SELECT * FROM categories WHERE id = ? AND is_active = 1").get(category_id);
  if (!category) {
    return res.status(400).json({ error: "Selected category was not found or is inactive." });
  }

  // Item IDs are always generated by the system — never accepted from the client.
  const code = nextItemCode(category_id);

  const tx = db.transaction(() => {
    const info = db
      .prepare(
        `INSERT INTO items(code, name, description, unit, quantity_on_hand, reorder_level, category_id, is_active, created_by, created_at)
         VALUES (?,?,?,?,?,?,?,1,?,?)`
      )
      .run(
        code,
        name,
        description || "",
        unit,
        Number(quantity_on_hand) || 0,
        Number(reorder_level) || 0,
        category_id,
        req.user.id,
        nowIso()
      );
    const itemId = info.lastInsertRowid;

    const insertPkg = db.prepare(
      `INSERT INTO item_packagings(item_id, label, units_per_pack, is_default, is_active, created_at) VALUES (?,?,?,?,1,?)`
    );
    const validPackagings = Array.isArray(packagings)
      ? packagings.filter((p) => p && p.label && Number(p.units_per_pack) > 0)
      : [];
    if (validPackagings.length === 0) {
      insertPkg.run(itemId, `Single ${unit}`, 1, 1, nowIso());
    } else {
      const hasDefault = validPackagings.some((p) => p.is_default);
      validPackagings.forEach((p, idx) => {
        const isDefault = hasDefault ? !!p.is_default : idx === 0;
        insertPkg.run(itemId, p.label, Number(p.units_per_pack), isDefault ? 1 : 0, nowIso());
      });
    }
    return itemId;
  });
  const itemId = tx();

  audit(req.user.id, req.user.email, "CREATE_ITEM", "ITEM", itemId, { code, name, category: category.name });
  notifyRoles(["inventoryadmin"], {
    type: "item_created",
    title: "New inventory item added",
    message: `${name} (${code}) was added under ${category.name}.`,
    entity_type: "ITEM",
    entity_id: itemId,
  });

  const item = db.prepare("SELECT * FROM items WHERE id = ?").get(itemId);
  res.status(201).json({ item: attachExtras(item) });
});

router.put("/:id", requireRole(...CAN_MANAGE_ITEMS), (req, res) => {
  const { id } = req.params;
  const { name, description, unit, reorder_level, category_id, is_active } = req.body || {};
  const item = db.prepare("SELECT * FROM items WHERE id = ?").get(id);
  if (!item) return res.status(404).json({ error: "Item not found." });

  if (category_id) {
    const category = db.prepare("SELECT * FROM categories WHERE id = ?").get(category_id);
    if (!category) return res.status(400).json({ error: "Selected category was not found." });
  }

  db.prepare(
    `UPDATE items SET
      name = COALESCE(?, name),
      description = COALESCE(?, description),
      unit = COALESCE(?, unit),
      reorder_level = COALESCE(?, reorder_level),
      category_id = COALESCE(?, category_id),
      is_active = COALESCE(?, is_active),
      updated_at = ?,
      updated_by = ?
     WHERE id = ?`
  ).run(
    name || null,
    description ?? null,
    unit || null,
    reorder_level ?? null,
    category_id || null,
    is_active === undefined ? null : is_active,
    nowIso(),
    req.user.id,
    id
  );

  audit(req.user.id, req.user.email, "UPDATE_ITEM", "ITEM", id, req.body);
  const updated = db.prepare("SELECT * FROM items WHERE id = ?").get(id);
  res.json({ item: attachExtras(updated) });
});

// ---- Packaging tiers (e.g. Single / Pack of 12 / Pack of 24 / Carton) ----
router.post("/:id/packagings", requireRole(...CAN_MANAGE_ITEMS), (req, res) => {
  const { id } = req.params;
  const { label, units_per_pack, is_default } = req.body || {};
  const item = db.prepare("SELECT * FROM items WHERE id = ?").get(id);
  if (!item) return res.status(404).json({ error: "Item not found." });
  if (!label || !(Number(units_per_pack) > 0)) {
    return res.status(400).json({ error: "A label and a positive units-per-pack value are required." });
  }

  const tx = db.transaction(() => {
    if (is_default) {
      db.prepare("UPDATE item_packagings SET is_default = 0 WHERE item_id = ?").run(id);
    }
    return db
      .prepare(
        `INSERT INTO item_packagings(item_id, label, units_per_pack, is_default, is_active, created_at) VALUES (?,?,?,?,1,?)`
      )
      .run(id, label, Number(units_per_pack), is_default ? 1 : 0, nowIso());
  });
  const info = tx();

  audit(req.user.id, req.user.email, "CREATE_PACKAGING", "ITEM", id, { label, units_per_pack });
  res.status(201).json({ item: attachExtras(db.prepare("SELECT * FROM items WHERE id = ?").get(id)), packaging_id: info.lastInsertRowid });
});

router.put("/packagings/:pid", requireRole(...CAN_MANAGE_ITEMS), (req, res) => {
  const { pid } = req.params;
  const { label, units_per_pack, is_default, is_active } = req.body || {};
  const packaging = db.prepare("SELECT * FROM item_packagings WHERE id = ?").get(pid);
  if (!packaging) return res.status(404).json({ error: "Packaging tier not found." });

  const tx = db.transaction(() => {
    if (is_default) {
      db.prepare("UPDATE item_packagings SET is_default = 0 WHERE item_id = ?").run(packaging.item_id);
    }
    db.prepare(
      `UPDATE item_packagings SET
        label = COALESCE(?, label),
        units_per_pack = COALESCE(?, units_per_pack),
        is_default = COALESCE(?, is_default),
        is_active = COALESCE(?, is_active)
       WHERE id = ?`
    ).run(
      label || null,
      units_per_pack ? Number(units_per_pack) : null,
      is_default === undefined ? null : (is_default ? 1 : 0),
      is_active === undefined ? null : (is_active ? 1 : 0),
      pid
    );
  });
  tx();

  audit(req.user.id, req.user.email, "UPDATE_PACKAGING", "ITEM", packaging.item_id, { packaging_id: pid, ...req.body });
  const item = db.prepare("SELECT * FROM items WHERE id = ?").get(packaging.item_id);
  res.json({ item: attachExtras(item) });
});

// Record incoming stock (increases quantity_on_hand). Restricted to inventory managers.
// Accepts either a packaging-based quantity ({ packaging_id, pack_qty }) or, for
// backward compatibility, a raw base-unit { qty }.
router.post("/:id/receive", requireRole(...CAN_RECEIVE_STOCK), (req, res) => {
  const { id } = req.params;
  const { packaging_id, pack_qty, qty, remarks } = req.body || {};
  const item = db.prepare("SELECT * FROM items WHERE id = ?").get(id);
  if (!item) return res.status(404).json({ error: "Item not found." });

  let baseQty;
  let usedPackagingId = null;
  let usedPackQty = null;

  if (packaging_id) {
    const packaging = db
      .prepare("SELECT * FROM item_packagings WHERE id = ? AND item_id = ? AND is_active = 1")
      .get(packaging_id, id);
    if (!packaging) return res.status(400).json({ error: "Selected packaging is invalid for this item." });
    const p = Number(pack_qty);
    if (!p || p <= 0) return res.status(400).json({ error: "Enter a quantity greater than zero." });
    baseQty = p * packaging.units_per_pack;
    usedPackagingId = packaging.id;
    usedPackQty = p;
  } else {
    baseQty = Number(qty);
    if (!baseQty || baseQty <= 0) {
      return res.status(400).json({ error: "Quantity must be a positive number." });
    }
  }

  const tx = db.transaction(() => {
    db.prepare("UPDATE items SET quantity_on_hand = quantity_on_hand + ? WHERE id = ?").run(baseQty, id);
    db.prepare(
      `INSERT INTO stock_receipts(item_id, qty, packaging_id, pack_qty, remarks, received_by, created_at) VALUES (?,?,?,?,?,?,?)`
    ).run(id, baseQty, usedPackagingId, usedPackQty, remarks || "", req.user.id, nowIso());
  });
  tx();

  audit(req.user.id, req.user.email, "RECEIVE_STOCK", "ITEM", id, { baseQty, packaging_id: usedPackagingId, pack_qty: usedPackQty, remarks });
  const updated = db.prepare("SELECT * FROM items WHERE id = ?").get(id);
  res.json({ item: attachExtras(updated) });
});

module.exports = router;
