// Shared PDF export for every report: renders the same institution letterhead
// used on the printed/HTML view (name, title, generated-by/on, filter summary)
// followed by a table built from the report's `columns` (so screen, CSV and
// PDF always agree on exactly which fields are included) and, optionally, a
// signature block matching the paper sign-off sheet.
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDateTime } from "./formatDate";

const GREEN_DARK = [11, 61, 31];
const GREEN = [15, 107, 44];
const GRAY = [108, 117, 125];

export function buildReportPdf({
  title,
  filtersSummary,
  generatedBy,
  columns,
  rows,
  summaryLines = [],
  signatureLabels = [],
  orientation = "landscape",
}) {
  const doc = new jsPDF({ orientation, unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 32;

  // ---- Letterhead ----
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...GREEN_DARK);
  doc.text("Plateau State University, Bokkos", margin, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("Store Management Information System", margin, 54);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...GREEN_DARK);
  doc.text(title, margin, 76);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  if (filtersSummary) doc.text(String(filtersSummary), margin, 90);

  const metaRight = [
    `Generated by: ${generatedBy || "—"}`,
    `Generated on: ${formatDateTime(new Date())}`,
  ];
  doc.text(metaRight, pageWidth - margin, 40, { align: "right" });

  doc.setDrawColor(...GREEN);
  doc.setLineWidth(1);
  doc.line(margin, 98, pageWidth - margin, 98);

  let cursorY = 112;

  // ---- Summary strip ----
  if (summaryLines.length) {
    doc.setFontSize(9);
    doc.setTextColor(33, 37, 41);
    doc.setFont("helvetica", "bold");
    const text = summaryLines.join("     |     ");
    doc.text(text, margin, cursorY);
    cursorY += 16;
  }

  // ---- Table ----
  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [columns.map((c) => c.label)],
    body: rows.map((row) => columns.map((c) => (c.csv ? c.csv(row) : row[c.key] ?? ""))),
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: GREEN, textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [244, 248, 245] },
    didDrawPage: () => {
      const pageCount = doc.internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(...GRAY);
      doc.text(
        `Page ${doc.internal.getCurrentPageInfo().pageNumber} of ${pageCount}`,
        pageWidth - margin,
        doc.internal.pageSize.getHeight() - 16,
        { align: "right" }
      );
      doc.text("PLASU BOKKOS — OFFICIAL COPY", margin, doc.internal.pageSize.getHeight() - 16);
    },
  });

  // ---- Signature block ----
  if (signatureLabels.length) {
    let sigY = doc.lastAutoTable.finalY + 48;
    const pageHeight = doc.internal.pageSize.getHeight();
    if (sigY > pageHeight - 60) {
      doc.addPage();
      sigY = 60;
    }
    const colWidth = (pageWidth - margin * 2) / signatureLabels.length;
    signatureLabels.forEach((label, idx) => {
      const x = margin + idx * colWidth;
      const text = typeof label === "object" ? label.label : label;
      const filled = typeof label === "object" ? label.filled || "" : "";
      doc.setFontSize(9);
      doc.setTextColor(33, 37, 41);
      doc.text(filled, x + colWidth / 2, sigY - 6, { align: "center" });
      doc.setDrawColor(33, 37, 41);
      doc.line(x + 8, sigY, x + colWidth - 8, sigY);
      doc.setFontSize(8);
      doc.setTextColor(...GRAY);
      doc.text(text, x + colWidth / 2, sigY + 12, { align: "center", maxWidth: colWidth - 16 });
    });
  }

  return doc;
}

export function downloadReportPdf(filename, options) {
  const doc = buildReportPdf(options);
  doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}
