import React from "react";
import { Table, Badge } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import { formatDateTime } from "../../utils/formatDate";

// Printable audit trail: the same accountability log shown on screen, with
// the official letterhead for when a regulator or management asks for a
// signed, dated activity record rather than a live screen.
export default function AuditLogPrint({ logs, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Audit Trail Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Total Entries", value: logs.length },
        ]}
      />

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>When</th>
            <th>Actor</th>
            <th>Action</th>
            <th>Entity</th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          {logs.map((log) => (
            <tr key={log.id}>
              <td>{formatDateTime(log.created_at)}</td>
              <td>
                {log.actor_name || "—"}
                {log.actor_email && <div className="text-muted small">{log.actor_email}</div>}
              </td>
              <td><Badge bg="secondary">{log.action}</Badge></td>
              <td>{log.entity_type} #{log.entity_id}</td>
              <td className="small">{log.details}</td>
            </tr>
          ))}
          {logs.length === 0 && (
            <tr><td colSpan={5} className="text-center text-muted">No activity recorded for the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Compiled By (ICT Admin)", "Reviewed By (Internal Audit)"]} />
    </div>
  );
}
