import React from "react";
import { Table } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import StatusBadge from "../StatusBadge";
import { formatDate, formatDateTime } from "../../utils/formatDate";

// Printable department summary/consumption report. In "all departments" mode
// it's a comparison table (who is requesting/consuming the most); when
// scoped to a single department it also lists the underlying requisitions.
export default function DepartmentSummaryReportPrint({ departments, summary, detail, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Department Summary Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Departments", value: summary.totalDepartments },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col">
          <strong>Departments:</strong> {summary.totalDepartments}
        </div>
        <div className="col">
          <strong>Total Requisitions:</strong> {summary.totalRequisitions}
        </div>
        <div className="col">
          <strong>Total Units Issued:</strong> {summary.totalUnitsIssued}
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>Department</th>
            <th className="text-end">Total</th>
            <th className="text-end">Pending</th>
            <th className="text-end">Recommended</th>
            <th className="text-end">Approved</th>
            <th className="text-end">Issued</th>
            <th className="text-end">Rejected</th>
            <th className="text-end">Units Issued</th>
            <th>Top Items Issued</th>
          </tr>
        </thead>
        <tbody>
          {departments.map((d) => (
            <tr key={d.department_id || d.department_name}>
              <td>{d.department_name}</td>
              <td className="text-end">{d.totalRequisitions}</td>
              <td className="text-end">{d.byStatus.pending || 0}</td>
              <td className="text-end">{d.byStatus.recommended || 0}</td>
              <td className="text-end">{d.byStatus.approved || 0}</td>
              <td className="text-end">{d.byStatus.issued || 0}</td>
              <td className="text-end">{d.byStatus.rejected || 0}</td>
              <td className="text-end">{d.totalUnitsIssued}</td>
              <td className="small">{d.topItems.map((t) => `${t.item_name} (${t.qty})`).join(", ") || "—"}</td>
            </tr>
          ))}
          {departments.length === 0 && (
            <tr><td colSpan={9} className="text-center text-muted">No requisitions match the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      {detail && detail.length > 0 && (
        <>
          <h6 className="mt-4">Requisition Detail — {departments[0]?.department_name}</h6>
          <Table bordered size="sm" className="mb-4">
            <thead>
              <tr>
                <th>SRV No.</th>
                <th>Requested By</th>
                <th>Purpose</th>
                <th>Items</th>
                <th>Status</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {detail.map((r) => (
                <tr key={r.id}>
                  <td>{r.req_no}</td>
                  <td>{r.hod_name}</td>
                  <td className="small">{r.purpose}</td>
                  <td className="small">{r.lines?.map((l) => `${l.item_name} (${l.qty_requested} ${l.unit})`).join(", ")}</td>
                  <td><StatusBadge status={r.status} /></td>
                  <td>{formatDate(r.created_at)}</td>
                </tr>
              ))}
            </tbody>
          </Table>
        </>
      )}

      <SignatureBlock labels={["Prepared By (Head of Store)", "Verified By (Internal Audit)", "Approved By (Registrar/ICT Admin)"]} />
    </div>
  );
}
