import React from "react";
import { Table, Badge } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import { formatDateTime } from "../../utils/formatDate";

// Printable inventory status report: every active item with its category,
// on-hand quantity (shown both as a friendly pack breakdown and the exact
// base-unit figure), reorder level and health flag.
export default function InventoryReportPrint({ items, summary, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Inventory Status Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Total Items", value: summary.totalItems },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col">
          <strong>Total Items:</strong> {summary.totalItems}
        </div>
        <div className="col">
          <strong>Low Stock:</strong> {summary.lowStockCount}
        </div>
        <div className="col">
          <strong>Categories:</strong> {Object.keys(summary.byCategory).length}
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>Code</th>
            <th>Item</th>
            <th>Category</th>
            <th>On Hand (Best Fit)</th>
            <th className="text-end">On Hand ({items[0]?.unit || "base unit"})</th>
            <th className="text-end">Reorder Level</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {items.map((i) => {
            const bestFit = i.breakdown?.parts?.length
              ? i.breakdown.parts.map((p) => `${p.count} × ${p.label}`).join(", ") +
                (i.breakdown.remainder ? ` + ${i.breakdown.remainder} ${i.unit}` : "")
              : `${i.quantity_on_hand} ${i.unit}`;
            const low = i.quantity_on_hand <= i.reorder_level;
            return (
              <tr key={i.id}>
                <td>{i.code}</td>
                <td>{i.name}</td>
                <td>{i.category_name || "—"}</td>
                <td>{bestFit}</td>
                <td className="text-end">{i.quantity_on_hand}</td>
                <td className="text-end">{i.reorder_level}</td>
                <td>
                  {low ? <Badge bg="warning" text="dark">Low</Badge> : <Badge bg="success">Healthy</Badge>}
                </td>
              </tr>
            );
          })}
          {items.length === 0 && (
            <tr><td colSpan={7} className="text-center text-muted">No items match the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Prepared By (Store Officer)", "Verified By (Head of Store)", "Approved By (ICT Admin)"]} />
    </div>
  );
}
