import React from "react";
import { Table, Badge } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import { formatDateTime } from "../../utils/formatDate";

// Printable low-stock / reorder report: a focused, actionable list of what
// needs to be bought next, with a suggested reorder quantity per item so the
// person placing the order doesn't have to do the arithmetic by hand.
export default function LowStockReportPrint({ items, summary, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Low Stock / Reorder Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Items Needing Reorder", value: summary.totalLowStock },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col">
          <strong>Needing Reorder:</strong> {summary.totalLowStock}
        </div>
        <div className="col">
          <strong>Out of Stock:</strong> {summary.outOfStockCount}
        </div>
        <div className="col">
          <strong>Total Deficit (base units):</strong> {summary.totalDeficitUnits}
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>Code</th>
            <th>Item</th>
            <th>Category</th>
            <th className="text-end">On Hand</th>
            <th className="text-end">Reorder Level</th>
            <th className="text-end">Deficit</th>
            <th className="text-end">Suggested Order Qty</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {items.map((i) => (
            <tr key={i.id}>
              <td>{i.code}</td>
              <td>{i.name}</td>
              <td>{i.category_name || "—"}</td>
              <td className="text-end">{i.quantity_on_hand} {i.unit}</td>
              <td className="text-end">{i.reorder_level} {i.unit}</td>
              <td className="text-end">{i.deficit} {i.unit}</td>
              <td className="text-end">{i.suggested_order_qty} {i.unit}</td>
              <td>
                {i.quantity_on_hand <= 0 ? (
                  <Badge bg="danger">Out of Stock</Badge>
                ) : (
                  <Badge bg="warning" text="dark">Low</Badge>
                )}
              </td>
            </tr>
          ))}
          {items.length === 0 && (
            <tr><td colSpan={8} className="text-center text-muted">No items are currently below their reorder level.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Prepared By (Store Officer)", "Verified By (Head of Store)", "Approved For Purchase By (ICT Admin)"]} />
    </div>
  );
}
