import React from "react";
import { Table } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import StatusBadge from "../StatusBadge";

// Printable requisitions report. Works for every slice — a plain date-range
// listing, "by department" or "by person" (the grouped summary tables are
// included alongside the detail list so both views print on one document).
export default function RequisitionsReportPrint({ requisitions, summary, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Requisitions Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: new Date().toLocaleString() },
          { label: "Total Requisitions", value: summary.totalCount },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col-4">
          <strong>By Status</strong>
          <ul className="list-unstyled mb-0 small">
            {Object.entries(summary.byStatus).map(([k, v]) => (
              <li key={k}>{k}: {v}</li>
            ))}
          </ul>
        </div>
        <div className="col-4">
          <strong>By Department</strong>
          <ul className="list-unstyled mb-0 small">
            {Object.entries(summary.byDepartment).map(([k, v]) => (
              <li key={k}>{k}: {v}</li>
            ))}
          </ul>
        </div>
        <div className="col-4">
          <strong>By Person</strong>
          <ul className="list-unstyled mb-0 small">
            {Object.entries(summary.byPerson).map(([k, v]) => (
              <li key={k}>{k}: {v}</li>
            ))}
          </ul>
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>SRV No.</th>
            <th>Department</th>
            <th>Requested By</th>
            <th>Purpose</th>
            <th>Items</th>
            <th>Status</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {requisitions.map((r) => (
            <tr key={r.id}>
              <td>{r.req_no}</td>
              <td>{r.department_name_current || r.department}</td>
              <td>{r.hod_name}</td>
              <td>{r.purpose}</td>
              <td>{r.lines?.map((l) => `${l.item_name} (${l.qty_requested} ${l.unit})`).join(", ")}</td>
              <td><StatusBadge status={r.status} /></td>
              <td>{new Date(r.created_at).toLocaleDateString()}</td>
            </tr>
          ))}
          {requisitions.length === 0 && (
            <tr><td colSpan={7} className="text-center text-muted">No requisitions match the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Prepared By (Inventory Admin)", "Verified By (Internal Audit)", "Approved By (Registrar/ICT Admin)"]} />
    </div>
  );
}
