import React from "react";
import { Table, Badge } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import { formatDate, formatDateTime } from "../../utils/formatDate";

const ROLE_LABELS = { head_of_store: "Head of Store", issuance_officer: "Issuance Officer" };
const ROLES = ["head_of_store", "issuance_officer"];

function SignCell({ s }) {
  if (!s) return <span className="text-muted small">—</span>;
  return s.signed ? (
    <Badge bg="success" title={s.signed_at ? formatDateTime(s.signed_at) : ""}>✓ {s.signed_by_name}</Badge>
  ) : (
    <Badge bg="warning" text="dark">Pending</Badge>
  );
}

// Printable requisition clearance status report: shows how far each approved
// requisition has progressed through the two-party clearance sheet (Head of
// Store signs first, then the Issuance Officer) that gates issuing it.
export default function RequisitionSignoffReportPrint({ requisitions, summary, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Requisition Clearance Status Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Total Requisitions", value: summary.totalCount },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col">
          <strong>Fully Cleared:</strong> {summary.fullyCleared}
        </div>
        <div className="col">
          <strong>Pending Clearance:</strong> {summary.pendingCount}
        </div>
        <div className="col">
          <strong>Avg. Turnaround:</strong>{" "}
          {summary.averageTurnaroundHours !== null ? `${summary.averageTurnaroundHours.toFixed(1)} hrs` : "—"}
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>SRV No.</th>
            <th>Department</th>
            <th>Approved On</th>
            {ROLES.map((r) => <th key={r}>{ROLE_LABELS[r]}</th>)}
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {requisitions.map((r) => (
            <tr key={r.id}>
              <td>{r.req_no}</td>
              <td>{r.department_name_current || r.department}</td>
              <td>{formatDate(r.approved_at)}</td>
              {ROLES.map((role) => (
                <td key={role}><SignCell s={r.signoffs[role]} /></td>
              ))}
              <td>
                {r.fully_cleared
                  ? <Badge bg="success">Fully Cleared</Badge>
                  : <Badge bg="warning" text="dark">{r.pending_roles.length} Pending</Badge>}
              </td>
            </tr>
          ))}
          {requisitions.length === 0 && (
            <tr><td colSpan={6} className="text-center text-muted">No approved/issued requisitions match the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Compiled By (Head of Store)", "Reviewed By (Internal Audit)"]} />
    </div>
  );
}
