import React from "react";
import { Table, Badge } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import { formatDate, formatDateTime } from "../../utils/formatDate";

const ROLE_LABELS = { technical_expert: "Technical Expert", audit_officer: "Audit Officer", asset_officer: "Asset Officer" };
const ROLES = ["technical_expert", "audit_officer", "asset_officer"];

function SignCell({ s }) {
  if (!s) return <span className="text-muted small">—</span>;
  return s.signed ? (
    <Badge bg="success" title={s.signed_at ? formatDateTime(s.signed_at) : ""}>✓ {s.signed_by_name}</Badge>
  ) : (
    <Badge bg="warning" text="dark">Pending</Badge>
  );
}

// Printable stock-receipt clearance status report: one row per clearance
// request (a date-range batch of stock receipts the Head of Store submits),
// showing each of the three officers' signatures and how long clearance took.
export default function StockClearanceReportPrint({ clearanceRequests, summary, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Stock Receipt Clearance Status Report"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Total Requests", value: summary.totalCount },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col">
          <strong>Cleared:</strong> {summary.fullyCleared}
        </div>
        <div className="col">
          <strong>Pending:</strong> {summary.pendingCount}
        </div>
        <div className="col">
          <strong>Avg. Turnaround:</strong>{" "}
          {summary.averageTurnaroundHours !== null ? `${summary.averageTurnaroundHours.toFixed(1)} hrs` : "—"}
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>Ref No.</th>
            <th>Period</th>
            <th>Submitted By</th>
            <th className="text-end">Receipts</th>
            {ROLES.map((r) => <th key={r}>{ROLE_LABELS[r]}</th>)}
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {clearanceRequests.map((c) => (
            <tr key={c.id}>
              <td>{c.ref_no}</td>
              <td className="small">{formatDate(c.date_from)} – {formatDate(c.date_to)}</td>
              <td>{c.created_by_name}</td>
              <td className="text-end">{c.receipt_count}</td>
              {ROLES.map((role) => (
                <td key={role}><SignCell s={c.signoffs[role]} /></td>
              ))}
              <td>
                {c.fully_cleared
                  ? <Badge bg="success">Cleared</Badge>
                  : <Badge bg="warning" text="dark">{c.pending_roles.length} Pending</Badge>}
              </td>
            </tr>
          ))}
          {clearanceRequests.length === 0 && (
            <tr><td colSpan={8} className="text-center text-muted">No clearance requests match the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Compiled By (Head of Store)", "Reviewed By (Internal Audit)"]} />
    </div>
  );
}
