import React from "react";
import { Table, Badge } from "react-bootstrap";
import Letterhead from "./Letterhead";
import SignatureBlock from "./SignatureBlock";
import { formatDate, formatDateTime } from "../../utils/formatDate";

// Printable stock-movements (receipts) report: the receiving-side ledger of
// everything that has come into the store, who recorded it, in what
// packaging, and whether it has been swept into a stock-receipt clearance
// request yet — used for stock reconciliation and audit trails.
export default function StockMovementsReportPrint({ receipts, summary, filtersSummary, generatedBy }) {
  return (
    <div className="print-page">
      <Letterhead
        title="Stock Movements Report (Receipts)"
        subtitle={filtersSummary}
        meta={[
          { label: "Generated By", value: generatedBy },
          { label: "Generated On", value: formatDateTime(new Date()) },
          { label: "Total Receipts", value: summary.totalReceipts },
        ]}
      />

      <div className="row mb-3 report-summary-row">
        <div className="col">
          <strong>Total Receipts:</strong> {summary.totalReceipts}
        </div>
        <div className="col">
          <strong>Total Units Received:</strong> {summary.totalUnitsReceived}
        </div>
        <div className="col">
          <strong>Awaiting Clearance:</strong> {summary.unclearedCount}
        </div>
      </div>

      <Table bordered size="sm" className="mb-4">
        <thead>
          <tr>
            <th>Date</th>
            <th>Item Code</th>
            <th>Item</th>
            <th>Category</th>
            <th>Packaging</th>
            <th className="text-end">Qty Received</th>
            <th>Received By</th>
            <th>Clearance</th>
            <th>Remarks</th>
          </tr>
        </thead>
        <tbody>
          {receipts.map((r) => (
            <tr key={r.id}>
              <td>{formatDate(r.created_at)}</td>
              <td>{r.item_code}</td>
              <td>{r.item_name}</td>
              <td>{r.category_name || "—"}</td>
              <td>{r.pack_qty ? `${r.pack_qty} × ${r.packaging_label}` : "—"}</td>
              <td className="text-end">{r.qty} {r.unit}</td>
              <td>{r.received_by_name || "—"}</td>
              <td>
                {r.clearance_status === "cleared" ? (
                  <Badge bg="success">Cleared ({r.clearance_ref_no})</Badge>
                ) : r.clearance_ref_no ? (
                  <Badge bg="warning" text="dark">Pending ({r.clearance_ref_no})</Badge>
                ) : (
                  <Badge bg="secondary">Not Submitted</Badge>
                )}
              </td>
              <td className="small">{r.remarks || "—"}</td>
            </tr>
          ))}
          {receipts.length === 0 && (
            <tr><td colSpan={9} className="text-center text-muted">No stock receipts match the selected filters.</td></tr>
          )}
        </tbody>
      </Table>

      <SignatureBlock labels={["Prepared By (Head of Store)", "Verified By (Internal Audit)"]} />
    </div>
  );
}
